### ISSUE TITLE
Postgres converter support for enums

### ISSUE THREAD

**Issue by mjperrone** [gabledata/recap#415]
It appears that the postgres -> recap converter currently does not support enums. It looks like there is no reference to `enum` in [the postgres converter code](https://github.com/recap-build/recap/blob/main/recap/converters/postgresql.py). I also don't see any tests referencing enum in [the postgres client integration tests](https://github.com/recap-build/recap/blob/main/tests/integration/clients/test_postgresql.py).

I'm having some trouble getting my local recap dev env working, so I haven't tested this test, but I think this test in this PR should show the limitation:

https://github.com/recap-build/recap/pull/414

**Comment by mjperrone** [comment]
Looks like this should reveal the valid enum types:

```sql
SELECT unnest(enum_range(NULL::test_enum_type_mood));
 unnest 
--------
 sad
 ok
 happy
(3 rows)
```

**Comment by criccomini** [comment]
Ohh, this one's going to be tricky in the same way that PG array dimensions and types was tricky (#411).

It looks like we need to use `udt_` stuff in the `information_schema.columns` view and also the `pg_enum` view to get the possible enum values.

*EDIT: Gah, didn't see your second comment. Yea, that would be an alternative way to get the valid enum types.*

---

![Screenshot 2024-01-17 at 3 34 58 PM](https://github.com/recap-build/recap/assets/167569/c96e6d0d-889c-4395-9f39-a7f626e4e2fc)
![Screenshot 2024-01-17 at 3 35 11 PM](https://github.com/recap-build/recap/assets/167569/c5bc2771-9a68-436b-9edf-82e0c5622e10)

**Comment by criccomini** [comment]
I'm also curious how PG handles arrays of enums. I expect it to enforce valid values for the arrays, but given that it doesn't enforce dimensions, it's worth poking at this to make sure.
