### ISSUE TITLE
Support default values in Postgresql converter

### ISSUE THREAD

**Issue by mjperrone** [gabledata/recap#417]
Postgres supports setting [default values for column values](https://www.postgresql.org/docs/current/ddl-default.html). Recap also [supports default values](https://recap.build/specs/type/0.3.0/#defaults).

Postgres reveals the default value in the [information schema](https://www.postgresql.org/docs/current/infoschema-columns.html), `column_default` column. This should already be grabbed in the [client query](https://github.com/recap-build/recap/blob/aaf306e6019bd5cbd262993d65a347d95eb8c6e6/recap/clients/postgresql.py#L92), so it could be used in the postgresql [converter](https://github.com/mjperrone/recap/blob/main/recap/converters/postgresql.py) with `column_props["COLUMN_DEFAULT"]` to set the right value in the `RecapType` instantiation.

This came to my attention in https://github.com/recap-build/recap/pull/414#issuecomment-1899182470

**Comment by criccomini** [comment]
@mjperrone I'll take a look at this one. Thanks for raising it.

**Comment by criccomini** [comment]
@mjperrone I'm not 100% sure what you're seeing broken. The [`tests/integration/clients/test_postgresql.py`](https://github.com/recap-build/recap/blob/main/tests/integration/clients/test_postgresql.py) test validates that both default=null and default=1 works:

```
                test_bigint BIGINT,
...
                test_not_null_default INTEGER NOT NULL DEFAULT 1,
```

These are validated here:

```
            UnionType(
                default=None,
                name="test_bigint",
                types=[NullType(), IntType(bits=64, signed=True)],
            ),
...
            IntType(bits=32, signed=True, name="test_not_null_default", default="1"),
```

And these validations are run for both:

```
test_struct_method_arrays_no_enforce_dimensions
test_struct_method_arrays_enforce_dimensions
```

The code that sets the default is here:

https://github.com/recap-build/recap/blob/main/recap/converters/dbapi.py#L20

**Comment by mjperrone** [comment]
That convinces me.
I saw a related error when I was implementing the enums, and then went looking in the postgresql client (not realizing it was a subclass of dbapi) and the postgres converter, and saw no references to `default`.

That's what I get for not also making a failing test to prove the issue :D

I'll close this, my fault!
